server:
  port: 8086
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8888/realms/facebook-clone
  data:
    mongodb:
      uri: mongodb://mongoadmin:password@localhost:27017/notification_db?authSource=admin
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: notification-group
      auto-offset-reset: earliest

  mvc:
    cors:
      enabled: false

app:
  services:
    post-service-url: http://localhost:8082
    user-service-url: http://localhost:8081

springdoc:
  swagger-ui:
    oauth:
      client-id: api-gateway
      use-pkce-with-authorization-code-grant: true
      scopes:
        - openid
        - profile
  oauth2:
    authorization-url: http://localhost:8088/realms/facebook-clone/protocol/openid-connect/auth
    token-url: http://localhost:8888/realms/facebook-clone/protocol/openid-connect/token