server:
  port: 8084

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8888/realms/facebook-clone

  data:
    redis:
      host: localhost
      port: 6379

  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: newsfeed-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: com.huyhieu.common.dto.event.PostCreatedEvent

  mvc:
    cors:
      enabled: false

app:
  services:
    social-service-url: http://localhost:8083
    post-service-url: http://localhost:8082



springdoc:
  swagger-ui:
    oauth:
      client-id: api-gateway
      use-pkce-with-authorization-code-grant: true
      scopes:
        - openid
        - profile
  oauth2:
    authorization-url: http://localhost:8088/realms/facebook-clone/protocol/openid-connect/auth
    token-url: http://localhost:8888/realms/facebook-clone/protocol/openid-connect/token