version: '3.8'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.4.0
    container_name: keycloak
    command: start
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HTTP_ENABLED: true
      KC_LOG_LEVEL: INFO
      KEYCLOAK_FRONTEND_URL: http://localhost:8180
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: true
      # Trỏ đến CSDL 'keycloak_db' mới
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://db:5432/keycloak_db
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: password
      # 1. Tên topic cho User events (topicEvents)
      KAFKA_TOPIC: keycloak_user_events
      # 2. Tên topic cho Admin events (topicAdminEvents)
      KAFKA_ADMIN_TOPIC: keycloak_admin_events
      # 3. Địa chỉ Kafka (bootstrapServers)
      KAFKA_BOOTSTRAP_SERVERS: kafka:9094
      # 4. Tên client ID cho Kafka (clientId)
      KAFKA_CLIENT_ID: keycloak-producer
      KAFKA_EVENTS: CREATE,UPDATE,DELETE
    ports:
      - "8888:8080"
    volumes:
      # 4. Mount thư mục plugin vào container Keycloak
      - ./keycloak-plugins:/opt/keycloak/providers
    networks:
      - app-network
    depends_on:
      - db
      - kafka

  db:
    image: postgres:15-alpine
    container_name: postgres_db
    environment:
      - POSTGRES_DB=user_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    networks:
      - app-network
    volumes: # (Tùy chọn) Giữ data khi restart container
      - postgres-data:/var/lib/postgresql/data
      # create db keycloak-db
      - ./init-keycloak-db.sh:/docker-entrypoint-initdb.d/init-keycloak-db.sh

  kafka:
    image: apache/kafka:4.1.0 # (Giữ nguyên)
    platform: linux/amd64
    hostname: kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093,INTERNAL://0.0.0.0:9094
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.1.42:9092,INTERNAL://kafka:9094
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,INTERNAL:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_NUM_PARTITIONS: 1
      KAFKA_LOG_RETENTION_HOURS: 24
    networks:
      - app-network
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8989:8080" # Chúng ta sẽ truy cập UI ở cổng 8989
    environment:
      # Tên hiển thị cho cluster
      KAFKA_CLUSTERS_0_NAME: local-kafka-cluster
      # Địa chỉ Kafka (BÊN TRONG DOCKER)
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9094
    networks:
      - app-network
    depends_on:
      - kafka # Khởi động sau khi kafka khởi động

  mongo:
    image: mongo:latest
    container_name: mongo_db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=post_db
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

  minio:
    image: minio/minio:latest
    container_name: minio_storage
    ports:
      - "9000:9000" # Cổng API
      - "9001:9001" # Cổng Giao diện Web
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=password
    volumes:
      - minio-data:/data
    command: server /data --console-address ":9001"
    networks:
      - app-network

  neo4j:
    image: neo4j:5-community
    container_name: neo4j_db
    ports:
      - "7474:7474" # Giao diện Web (UI)
      - "7687:7687" # Cổng Bolt (cho Spring Boot kết nối)
    environment:
      - NEO4J_AUTH=neo4j/password
    volumes:
      - neo4j-data:/data
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    container_name: redis_cache
    ports:
      - "6379:6379"
    networks:
      - app-network

  cassandra:
    platform: linux/amd64
    image: cassandra:4
    container_name: cassandra_db
    ports:
      - "9042:9042" # Cổng kết nối (CQL)
    volumes:
      - cassandra-data:/var/lib/cassandra
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
  mongo-data:
  minio-data:
  neo4j-data:
  cassandra-data: