server:
  port: 8082

app:
  services:
    interaction-service-url: http://localhost:8085
    user-service-url: http://localhost:8081

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8888/realms/facebook-clone

  data:
    mongodb:
      uri: mongodb://mongoadmin:password@localhost:27017/post_db?authSource=admin

  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  mvc:
    cors:
      enabled: false

minio:
  url: http://localhost:9000
  access-key: minioadmin
  secret-key: password
  bucket-name: facebook-posts
  expiry: 3600  # 1h

springdoc:
  swagger-ui:
    oauth:
      client-id: api-gateway
      use-pkce-with-authorization-code-grant: true
      scopes:
        - openid
        - profile
  oauth2:
    authorization-url: http://localhost:8088/realms/facebook-clone/protocol/openid-connect/auth
    token-url: http://localhost:8888/realms/facebook-clone/protocol/openid-connect/token