server:
  port: 8081 # Service này chạy ở cổng 8081

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8888/realms/facebook-clone

  datasource:
    url: jdbc:postgresql://localhost:5432/user_db
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update # Tự động tạo/cập nhật bảng khi khởi động
    show-sql: true # Hiển thị câu lệnh SQL trong log

  kafka:
    bootstrap-servers: localhost:9092  # connect tới broker Docker qua localhost
    consumer:
      group-id: user-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.huyhieu.userservice.*"
        spring.json.value.default.type: com.huyhieu.userservice.dto.response.AdminEventDto
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
